export class UsersTable {
	public static users: any = [
		{
			id: 1,
			first_name: 'Denish',
			last_name: 'Sonani',
			email: 'denishsonani19@gmail.com',
			phone_no: '8690055919',
			village_id: 'Amreli',
			role_id: 'Manager',
			area_id: 'Katargam',
			birth_date: '1992/07/21',
			is_main_member: 1,
			main_member_id: '-',
			gender: '1',
			block_no: 'D',
			address: 'D-1, Sudarshan',
			city: 'Surat',
			state: 'Gujarat',
			postcode: '395010',
			is_active: 1,
			profile: 'https://pbs.twimg.com/profile_images/920063296387944449/71cqAAP3.jpg',
		},
		{
			id: 2,
			first_name: 'Bhavik',
			last_name: 'Moradiya',
			email: 'bhavik.moradiya@gmail.com',
			phone_no: '8956231245',
			village_id: 'Vallabhipur',
			role_id: 'Manager',
			area_id: 'Varachha',
			birth_date: '1992/06/26',
			is_main_member: 1,
			main_member_id: '-',
			gender: '1',
			block_no: 'A',
			address: 'A-1, Sudarshan',
			city: 'Surat',
			state: 'Gujarat',
			postcode: '395010',
			is_active: 1,
			profile: 'https://lh3.googleusercontent.com/-o_KJT_ADJAU/AAAAAAAAAAI/AAAAAAAABHE/oIr6Iy-D5uM/s640-il/photo.jpg',
		},
		{
			id: 3,
			first_name: 'Chetan',
			last_name: 'Nakum',
			email: 'chetan.nakum@gmail.com',
			phone_no: '7845122356',
			village_id: 'Amreli',
			role_id: 'Manager',
			area_id: 'Katargam',
			birth_date: '1990/05/25',
			is_main_member: 1,
			main_member_id: '-',
			gender: '1',
			block_no: 'B',
			address: 'B-1, Sudarshan',
			city: 'Surat',
			state: 'Gujarat',
			postcode: '395010',
			is_active: 1,
			profile: 'https://plus.google.com/_/focus/photos/public/AIbEiAIAAABDCM6hm46XiOLDLSILdmNhcmRfcGhvdG8qKDJjZjE3YTRjYTJmYmM4MjFiYWQ2Zjk4MjBmYWUzMmY4MWZkNTdhZTkwAUkqBZAM2eNr2L6q3xqUM2oisg_3?sz=128',
		},
		{
			id: 4,
			first_name: 'Yogesh',
			last_name: 'Jalodara',
			email: 'yogi.jalodara@gmail.com',
			phone_no: '8978455623',
			village_id: 'Vallabhipur',
			role_id: 'Manager',
			area_id: 'Varachha',
			birth_date: '1990/01/02',
			is_main_member: 1,
			main_member_id: '-',
			gender: '1',
			block_no: 'C',
			address: 'C-1, Sudarshan',
			city: 'Surat',
			state: 'Gujarat',
			postcode: '395010',
			is_active: 1,
			profile: 'https://naukrirecruiter.naukri.com/profilePic/getpic?pid=1474542822rp2908728_medium4',
		}
	];
}
